### ISSUE TITLE
初始化所需的资源获取

### ISSUE THREAD

**Issue by DazeCake** [arkntools/depot-recognition#1]
文档中给出的材料json和pkg文件路径已经失效，请问是否能提供一个自动化同步远程仓库到本地例如[Arknights-Bot-Resource](https://github.com/yuanyan3060/Arknights-Bot-Resource)以拉取最新资源的方式呢

**Comment by Tsuk1ko** [comment]
噢，因为数据源迁移到 https://github.com/arkntools/arknights-toolbox-data 了，我忘记更新文档了，过会更新下

**Comment by DazeCake** [comment]
好的，非常感谢
